name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome to the community and thank you for adding this issue :)'' first issue'
        pr-message: 'Thank you for the contribution. Your hard work is greatly appreciated. Welcome to the community :)'' first pr'
